language: python
install:
  - travis_retry pip install -U -r requirements-doc.txt
  - travis_retry pip install -e .

script:
  - 'true'

after_success:
  - make -C docs html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master  # the default branch name
  local_dir: docs/build/html